apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: nginx
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: name@example.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
    solvers:
       - http01:
           ingress:
             class: nginx