apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
  labels:
    app: keycloak
data:
  DB_VENDOR: postgres
  DB_DATABASE: keycloak_stage
  DB_ADDR: postgres
  DB_PORT: "5432"
  KEYCLOAK_SCHEMA: keycloak #this value is required by keycloak